# -*- coding: utf-8 -*-
"""projetocalculadora.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NyymGDwy9jN32y_EYbvcEQtIPzQzClkh
"""

def formatar(numero):
    if numero == int(numero):
        return int(numero)
    return numero


def calcular(num1, operador, num2):
    if operador == '+':
        return num1 + num2
    elif operador == '-':
        return num1 - num2
    elif operador == '*':
        return num1 * num2
    elif operador == '/':
        return num1 / num2
    elif operador == '%':
        return num1 % num2
    elif operador == '//':
        return num1 // num2
    elif operador == '**':
        return num1 ** num2
    else:
        raise ValueError("Operador inválido!")


def main():
    print('=== CALCULADORA SIMPLES ===')
    print('Operadores disponíveis: + - * / % // **')

    while True:
        entrada1 = input("\nDigite o primeiro número (ou 'sair' para encerrar): ")
        if entrada1.lower() == 'sair':
            print("Encerrando a calculadora. Até mais!")
            break

        try:
            num1 = float(entrada1)
            operador = input("Digite o operador (+ - * / % // **): ").strip()
            num2 = float(input("Digite o segundo número: "))
            resultado = calcular(num1, operador, num2)
            print(f"Resultado: {formatar(num1)} {operador} {formatar(num2)} = {formatar(resultado)}")

        except ZeroDivisionError:
            print("Erro: não é possível dividir por zero!")

        except ValueError as e:
            if str(e) == "Operador inválido!":
                print("Erro: operador inválido. Use + - * / % // **")
            else:
                print("Erro: digite um número válido!")

        except Exception as e:
            print(f"Ocorreu um erro inesperado: {e}")


if __name__ == "__main__":
    main()